spring.application.name=demo

server.address=0.0.0.0
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:eco_store}?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${MYSQLUSER:root}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${MYSQLPASSWORD:}}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.datasource.hikari.maximum-pool-size=20
